import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'hello',
    {
      type: 'category',
      label: 'Signal Processing',
      items: ['signal-processing/congratulations'],
    },
    {
      type: 'category',
      label: 'Peripherals',
      items: ['peripherals/donkey_kong_bongos', 'peripherals/wii_nunchuck', 'peripherals/nes_controller'],
    },
    {
      type: 'category',
      label: 'Graphics',
      items: ['graphics/ping_pong_ram', 'graphics/sdram_controller', 'graphics/color_composition', 'graphics/update_only_graphics_generator'],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      items: ['miscellaneous/congratulations'],
    },
  ],
   
};

export default sidebars;
