name: main-workflow
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy app
        run: |
          pwd
          GIT_USER=amidthestars yarn deploy
