name: main-workflow
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./my-website
    steps:
      - uses: actions/checkout@v3
      - name: Deploy app
        run: GIT_USER=amidthestars yarn deploy
